### ISSUE TITLE
Memory footprint reduction strategies of large structs for potential substantial performance improvements?

### ISSUE THREAD

**Issue by richarddd** [quickjs-ng/quickjs#475]
Hey all,

I've just watched a [fantastic Data Driven Design presentation by Andrew Kelly](https://www.youtube.com/watch?v=IroPQ150F6c) (creator of the Zig programming language).

He talks about how to apply some memory footprint reduction strategies that drastically reduces memory, also reduces cache misses, fixes alignment and padding and much more. This introduced substantial performance improvements for heavily used structs.

The strategies mentioned in the presentation are:

1. Use indexes instead of pointes
2. Store booleans out-of-band
3. Eliminate padding with struct-of-arrays
4. Use sparse data in hash maps
5. Use "encodings" instead of OOP or Polymorphism with an "extra" index

I then wondered if these strategies could be applied in heavily used structs in QJS as well, such as `JSObject` or `JSShape`.

Looking at, for example, the `JSObject` struct it contains a lot of pointers, bool and nested structs.

What if `JSObject` instead looked something like this:
```c
struct JSObject {
    uint32_t shape_index;  // Index into a global shape pool (array list), replaces JSShape *shape
    uint32_t prop_index;   // Index into a global property pool (array list), replaces JSProperty *prop
    uint32_t weak_ref_index;  // Index into weak reference table, replaces first_weak_ref pointer
    uint16_t class_id;     // Keeps original class_id, defines object type (JS_CLASS_x)
    uint8_t type_encoding; // Encodes specific object type, replaces large union
    uint8_t flags;         // Combines all boolean flags into one byte:
                           // bit 0: extensible
                           // bit 1: free_mark
                           // bit 2: is_exotic
                           // bit 3: fast_array
                           // bit 4: is_constructor
                           // bit 5: is_uncatchable_error
                           // bit 6: tmp_mark
                           // bit 7: is_HTMLDDA
    uint32_t data_index;   // Index into type-specific data array, replaces union u
};
```
This would take up about 20(+4 padding) bytes per `JSObject`, instead of 72.

I'm not a C programmer or a low-level performance expert by any means. Maybe the increased indirection would regress performance instead of improving it? I also do recognize that this will be a huge refactor and introduce additional risks (such as type safety).

LMKWYT

**Comment by KaruroChori** [comment]
I think you missed several aspects:
- Those booleans are already all combined. They are specified like `uint8_t extensible : 1;` and the last digit will determine the number of bits for a given field. So you are not using one byte for one boolean. Your solution is just worse.
- The benefits of padding/aligning and by which extent are platform dependent. So we usually let compilers deal with that, unless we are trying to match binary compatibility for a protocol, or we just know we are better.
- Why would you replace many of the current data structures with array lists? Why replacing all pointers with indeces? You would be adding more complexity in code to compute the final address, for no real advantage if not the more compact size of those objects on **some** architectures. Just because rust is unable to use pointers properly, if we are not getting its advantages at the very least it would be nice not to get its drawbacks :D
- Unions have no intrinsic overhead in C, so I really don't get why you want to purge them from code :/

From an abstract perspective I mostly agree with many of the abstract points you raised, derived from Kelly's talk, but they cannot be intended as absolutes and their applicability really depends on what your language is giving you. 
C has no comptime, so many of the great strategies to reshape data structures at compile time which are possible in Zig cannot be done in C. So while some of those points might have merit in principle, they cannot be effectively applied.

**Comment by richarddd** [comment]
I think me having so little experience with C really shows, I didn’t know about the boolean packing 👏
Using indexes instead of pointers is derived from Kelly’s presentation and refers from this blog post:
https://floooh.github.io/2018/06/17/handles-vs-pointers.html
Again was used to reduce memory (on 64 bit targets) and improve cache hit rates as similar data is stored together.
The same approach is why the union was removed to have dedicated arrays for similar objects.
I know C doesn’t have something fancy as comptime but that just applies for the Struct-of-arrays and ArrayList type erasure in this example.

**Comment by bnoordhuis** [comment]
> indexes instead of pointers

`ptr = base + index` won't work because there's no single base. Memory is allocated by the embedder (e.g. through malloc), not quickjs, so the address is basically arbitrary and random.

The other points don't seem very actionable to me, they're either not relevant, already implemented, or not reasonable to implement, as elaborated by @KaruroChori.

The best we can probably do is identify holes in structs and reorder fields appropriately, but a) that's abi/arch/platform specific, and b) quickjs probably is already reasonably well-behaved in that respect. I don't expect huge wins there.

**Comment by richarddd** [comment]
Thanks for explanation @bnoordhuis, makes sense!
