### ISSUE TITLE
Group custom globals in a `qjs` namespace?

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#736]
We currently have the following (custom) globals:

- argv0
- __argv (in PR)
- print
- scriptArgs

Would it make sense to make them part of some `qjs` global? IIRC some of those came from when we were running the V8 test suite, and some others were there originally, since the Mozilla shell had them too.

Thoughts?

/cc @bnoordhuis

**Comment by bnoordhuis** [comment]
print and gc are convenient to have as top-level globals (and pretty much all shells expose them that way), no strong opinion on the others. I'm weakly -0.1 on namespacing cuz extra keystrokes.

argv0 was indeed added for the now gone V8 test suite runner so it can go too, for all I care. It _is_ documented now in docs/docs/stdlib.md but I doubt anyone is going to miss it.

**Comment by bnoordhuis** [comment]
Apropos `__argv`, node calls that `process.execArgv`. I wouldn't add `process` because that undoubtedly breaks scripts that feature-detect node but `execArgv` or (if you must) `qjs.execArgv` makes it just that little bit more consistent with other runtimes.

edit: on the other hand execArg`v` vs. scriptArg`s` is kind of jarring :shrug:

**Comment by saghul** [comment]
execArgv SGTM, I'm happy to change that one if you agree!

**Comment by bnoordhuis** [comment]
Let's go with execArgv :)
