### ISSUE TITLE
API proposal: New zero copy JSString from utf8 heap buffer.

### ISSUE THREAD

**Issue by richarddd** [quickjs-ng/quickjs#768]
This would be useful so caller can pass ”ownership” of a heap allocated utf8 string.

For example we can pass a Rust string (which is already guaranteed to be utf8) without copying.

This is naturally a bit dangerous as caller must assure string is heap allocated and utf8.

Toughs?

**Comment by saghul** [comment]
We already have that concept for array buffers, so I'd say sure!

**Comment by bnoordhuis** [comment]
Passing a heap pointer won't work because JSString instances are variable-length objects; the string bytes are right after the string object. Introducing indirection by adding a pointer field to JSString both makes JSSstring bigger and string operations slower.

Also, how would Rust land know when it's safe to free the string? Strings don't have finalizers. I suppose qjs could call back to Rust from `js_free_string` and `js_free_value_rt` and other places where we free strings.

Would also require an update to `compute_jsstring_size` so it doesn't over-report memory usage.

**Comment by richarddd** [comment]
> Passing a heap pointer won't work because JSString instances are variable-length objects; the string bytes are right after the string object. Introducing indirection by adding a pointer field to JSString both makes JSSstring bigger and string operations slower.
> 
> Also, how would Rust land know when it's safe to free the string? Strings don't have finalizers. I suppose qjs could call back to Rust from `js_free_string` and `js_free_value_rt` and other places where we free strings.
> 
> Would also require an update to `compute_jsstring_size` so it doesn't over-report memory usage.

My take is that Rust for example don’t free it but QJS would. In other words, Rust would transfer ownership to QJS, the values would not live simultaneously.

**Comment by saghul** [comment]
Ah but that could be problematic since they could use different allocators.

**Comment by richarddd** [comment]
Right, I didn’t think of that, that makes this way to complicated!

**Comment by richarddd** [comment]
@bnoordhuis @saghul what do you think about an API that simply does memcopy and no UTF8 check? `JS_NewUTF8String`.
This again is super useful when called can guarantee that string already is UTF8, for example Rust strings

**Comment by bnoordhuis** [comment]
We can't skip the UTF-8 check because internally quickjs makes a distinction between ASCII, UTF-8 with only codepoints < U+800, and UTF-8 outside that range that must be converted to two-byte encoding. We could add a fast path for Latin1 though.

It's technically possible to introduce UTF-8 strings besides the existing one-byte and two-byte encodings but updating all string APIs would be a massive amount of work and turn many O(1) algorithms into O(n).
